### ISSUE TITLE
プログレスバーのコミットの最新リリースが欲しいです

### ISSUE THREAD

**Issue by serinuntius** [soramugi/inco#1]
いつも便利に使わせてもらっているのですが、master最新コミット 763c5ce9cb07e1a93092bd3d2a319a4790aaaf1b のリリースがあれば便利だと思います！

**Comment by soramugi** [comment]
あんまり更新できてなくて申し訳ない🙇‍♂️
macOS CatalinaではWindowsビルドが出来なくて置きっぱなしになっていました。
頑張ってDockerビルドに対応して公開してみました
https://github.com/soramugi/inco/releases/tag/v0.1.2
ちょっと確認がちゃんと出来てませんが動くはず... よかったら確認してみてください

**Comment by serinuntius** [comment]
原因の解明はできていないのですが、0.1.2のリリースビルドではダウンロードが上手く動かないようです・・・。
とりあえずご報告まで

## 環境
- Max OSX 10.15.1（19B88）

## 


<img width="1792" alt="スクリーンショット 2020-03-13 15 44 09" src="https://user-images.githubusercontent.com/10571219/76604911-edd36800-6552-11ea-9dd2-82a9ac27f37f.png">

**Comment by soramugi** [comment]
原因特定できまして、パッケージ作成後にffmpegの展開が出来てなかったようです。
mac版 0.1.3 で動作するようになります！
